install.packages("gamlss")
library(gamlss)
data(dbbmi)
year <- 15
dt<-with(dbbmi,subset(dbbmi,age>year & age<year+1))
bmi15 <- dt$bmi
install.packages("gamlss.ggplots")
library(gamlss,ggplots)
gamlss.ggplots:::y_hist(bmi15)
air1 <- gamlss(bmi~age,data=dt,family=BCCG)
air2 <- gamlss(bmi~age,data=dt,family=BCPE)
air3 <- gamlss(bmi~age,data=dt,family=BCT)
air4 <- gamlss(bmi~age,data=dt,family=EXP)
air5 <- gamlss(bmi~age,data=dt,family=GB2)
air6 <- gamlss(bmi~age,data=dt,family=LNO)
GAIC(air1,air2,air3,air4,air5,air6)
plot(bmi~age,data=dt,col='purple')
lines(fitted(air2)~dt$age,col='red',lwd=1)
lines(fitted(air3)~dt$age,col='yellow',lwd=3)
hist<-histDist(dt$bmi,family=BCPE,nbins=30,line.col='green',line.wd='2',main='BCPE fitted over bmi data')
hist<-histDist(dt$bmi,family=BCT,nbins=20,line.col='maroon',line.wd='2',main='BCT fitted over bmi data')
